### ISSUE TITLE
Version 4.17.2 fails to compile

### ISSUE THREAD

**Issue by s8m** [dmhacker/arch-linux-surface#1]
If you can post 4.17 on the releases page it would be much appreciated. In the meantime, when trying to compile I receive this error:

```Applying Surface device patches ...
/home/user/arch-linux-surface/build-4.17.2/PKGBUILD: line 53: ../linux-surface/patches/4.17/*.patch: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

EDIT: As the error indicates, looks like the patches aren't in place yet for 4.17 (the 4.17 folder doesn't exist). Maybe it's not ready and I'm just impatient? :)

**Comment by mpv945** [comment]
[haijun@archlinux arch-linux-surface]$ cd build-4.17.2/
[haijun@archlinux build-4.17.2]$ MAKEFLAGS="-j4" makepkg -sc
chmod: 更改'/home/haijun/arch-linux-surface/build-4.17.2' 的权限: 不允许的操作

==> 错误： An unknown error has occurred. Exiting...
用户定义信号 1

**Comment by dmhacker** [comment]
Apologies. You were correct. The reason this was occurring was because jakeday hadn't made a 4.17 patch folder, so the PKGBUILD was looking at an empty folder. He's since published them, so you're good to go. I've also posted a 4.17.8 release. :)
