### ISSUE TITLE
DKMS kernel modules failing to build with 5.8.3-arch1-1-surface

### ISSUE THREAD

**Issue by han-so1omon** [dmhacker/arch-linux-surface#103]
I am running Manjaro Linux 20 on Surface Book 2. My kernel version is 5.8.3-arch1-1-surface.

I am getting build failures for DMKS kernel modules. This has happened with `surfacebook2_dgpu_hps`, `nvidia 450.57` (from nvidia-beta-dkms), and the virtualbox dkms modules (of which I forget the name). I am triggering builds by reinstalling `linux-surface` or `linux-surface-headers`. All of the build logs look pretty similar to below, complaining about `gcc/structleak_plugin`:

```
DKMS make.log for surfacebook2_dgpu_hps-0.1.0 for kernel 5.8.3-arch1-1-surface (x86_64)
mar 25 ago 2020 22:29:12 -05
make -C /lib/modules/5.8.3-arch1-1-surface/build M=/var/lib/dkms/surfacebook2_dgpu_hps/0.1.0/build modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/lib/modules/5.8.3-arch1-1-surface/build'
  CC [M]  /var/lib/dkms/surfacebook2_dgpu_hps/0.1.0/build/surfacebook2_dgpu_hps.o
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/surfacebook2_dgpu_hps/0.1.0/build/surfacebook2_dgpu_hps.o] Error 1
make[1]: *** [Makefile:1756: /var/lib/dkms/surfacebook2_dgpu_hps/0.1.0/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.8.3-arch1-1-surface/build'
make: *** [Makefile:9: all] Error 2

```

What to make of this? Have you encountered this before? In any case, do you have any fix/debug suggestions?

**Comment by han-so1omon** [comment]
It seems like there is a shared library that may be built for a non-current version of gcc? In `/usrlib/modules/5.8.3-arch1-1-surface/build/scripts/gcc-plugins/`, there is a pre-built `structleak_plugin.so` file, and in the `structleak_plugin.c` file the comment at the top says that `Usage: for 4.5/4.6/C based 4.7`

**Comment by han-so1omon** [comment]
Output of `strings -a /usr/lib/modules/5.8.3-arch1-1-surface/build/scripts/gcc-plugins/structleak_plugin.so | grep "GCC: ("`
`GCC: (GNU) 10.2.0`

Output of `gcc --version`
`gcc(GCC) 10.1.0`

I am using `gcc` from `core/gcc`, which appears to be `v10.1.0-2` for Manjaro 20.1, but `core/gcc` is `v10.2.0-1` on [core repo site](https://www.archlinux.org/packages/core/x86_64/gcc/)

**Comment by qzed** [comment]
Different gcc versions can cause that. External modules always have to be compiled with the version that the kernel has been compiled with, so you'll somehow have to get gcc `v10.2.0` running on Manjaro.

Also a note: The `surfacebook2_dgpu_hps` driver is outdated. It's been replaced by `surface_sam_hps` and is already included in the kernel.

**Comment by han-so1omon** [comment]
Thanks. I've switched to using `gcc` from the `manjaro/testing` branch, which uses a compatible verson. I'm gonna close this.
