### ISSUE TITLE
Latest release 4.18.20-1 doesn't work with surface pro 4

### ISSUE THREAD

**Issue by KeAWang** [dmhacker/arch-linux-surface#12]
I installed the prebuilt binaries of release 4.18.20-1 on my surface pro 4 but the right click button, touch screen, and the surface pen don't work even after installing and configuring xf86-input-wacom. 

Can someone look into this? Thanks!

**Comment by dmhacker** [comment]
This might be more of an issue on jakeday's side, since all I do is group his compilation utilities into a PKGBUILD. But maybe try looking into `config.gz` options for 4.18?

**Comment by qzed** [comment]
For the pen, see https://github.com/jakeday/linux-surface/issues/327. The trackpad button might be a configuration issue.

**Comment by dmhacker** [comment]
See #8 for the stylus.

**Comment by dmhacker** [comment]
Long-standing issue pertaining to an old kernel release, so I will be closing it. Try re-running the setup script with all options enabled, which will install libwacom and the latest firmware and will update mkinitcpio modules.
