### ISSUE TITLE
Update for 4.19

### ISSUE THREAD

**Issue by etnguyen03** [dmhacker/arch-linux-surface#17]
Is there any plan to update this packager for 4.19? Is it just changing the version select to accommodate for 4.19?

[Jakeday's kernel](https://github.com/jakeday/linux-surface) now supports 4.19.

**Comment by dmhacker** [comment]
I will be updating it today!

**Comment by dmhacker** [comment]
Done. Check the releases section, or run the commands to build the kernel on your machine.
