### ISSUE TITLE
Does mkinitcpio honor /etc/initramfs-tools/modules?

### ISSUE THREAD

**Issue by hjr265** [dmhacker/arch-linux-surface#22]
So I noticed that the setup.sh script adds this following file from jakeday's repository:

- https://github.com/jakeday/linux-surface/blob/master/root/etc/initramfs-tools/modules

And, I wasn't sure if this was actually being used by mkinitcpio in Arch Linux. I entered some random words as module names in the file, and ran mkinitcpio. It ran without errors.

Then, copied the module names to /etc/mkinitcpio.conf (in `MODULES=()`). And ran mkinitpcio again, and this time it included those modules (except "hid_generic", which it couldn't find).

Could it mean we were missing out on some _fix_ by Jakeday?

**Comment by dmhacker** [comment]
I'll take a look at this.

**Comment by Ghabry** [comment]
Thanks, adding the modules and doing mkinicpio fixed the non-working touchscreen on my Surface Pro 4 :+1:

**Comment by dmhacker** [comment]
Fixed! Add an option to copy over modules from /etc/initramfs-tools/modules to /etc/mkinitcpio.conf and then execute a mkinitcpio rebuild. See https://github.com/dmhacker/arch-linux-surface/commit/413cb7de18361d908504d93f1b11f6cbd65e7008. I'll make a separate post explaining the new touchscreen fixes. Thanks for the help.
