### ISSUE TITLE
Installed on Surface Pro 6 and rebooted but cant get into new kernel

### ISSUE THREAD

**Issue by thetylerwolfman** [dmhacker/arch-linux-surface#24]
I can run "uname -r" and am still on Linux 5.0.0

**Comment by SebastianM-C** [comment]
Did you select the surface kernel in the grub menu?

**Comment by dmhacker** [comment]
Echoing @SebastianM-C's comment, make sure you have the correct kernel selected in your bootloader. If you're using grub, you can set the -surface kernel as the default kernel to load using `grub-customizer`.
