### ISSUE TITLE
Setup not correctly installing files

### ISSUE THREAD

**Issue by ShapeShifter499** [dmhacker/arch-linux-surface#25]
I git cloned per the instructions and ran 'sudo sh setup.sh' from the repository root. I never get prompted for which surface I have. I want to install for Surface Go.

**Comment by ShapeShifter499** [comment]
Ok I see.  The part of "Install IPTS firmware to enable the touchscreen" was a bit misleading since touchscreen seemed to work ok.  You have to agree to this bit in order to get the script to install other non-touchscreen drivers like for wireless.  I think this part should be changed or clarified in the readme

**Comment by dmhacker** [comment]
You're right. I clarified the config option to prompt for "device-specific" firmware (includes stuff for touchscreen, wireless, GPU), rather than using "IPTS" as a prompt option. Should fix up any confusion people were having in the past. Thanks.
