### ISSUE TITLE
setup.sh skips mwlwifi_firmware.zip

### ISSUE THREAD

**Issue by hjr265** [dmhacker/arch-linux-surface#28]
It seems setup.sh doesn't do this part:

https://github.com/jakeday/linux-surface/blob/5c2a640308d7628f0af341531e078c996b1ba917/setup.sh#L211

But, isn't this firmware needed by the Surface Book 2?

**Comment by dmhacker** [comment]
Looks like it's needed for all models actually. I've added a section for installing mwlwifi firmware.
