### ISSUE TITLE
High core temps on idle

### ISSUE THREAD

**Issue by danieltpye** [dmhacker/arch-linux-surface#29]
Hello, first, thanks for this excellent work.

I have the same issue as has been reported by many others using the Jakeday kernel -- high core temps (70-88C) on idle and ~100C on load.

Everything else seems to work perfectly. Read all previous issues with other versions of the kernel and AUR package, but can't figure out the problem.

**Comment by qzed** [comment]
What device do you have? If you're on a SB2, have you checked you're booting into the right kernel (`uname -a`)?

**Comment by danieltpye** [comment]
Yes I'm on the SB2. I checked what kernel was booting and believe it's the correct one.

`Linux surface 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux`

**Comment by qzed** [comment]
`5.0.3-arch1-1-ARCH` is the generic Arch one. It should read something like `5.0.3-linux-surface`. Have you updated your bootloader config?

In case of grub `grub-mkconfig -o /boot/grub/grub.cfg` should to the trick, assuming that is your config path. If you have grub, you might also want to consider installing https://aur.archlinux.org/packages/grub-hook/ so you don't have to do this every time you update the kernel.

**Comment by danieltpye** [comment]
Ah silly mistake on my part (as usual). Config wasn't updated properly. Thanks for your help.
