### ISSUE TITLE
Surface book 2 15 touchscreen

### ISSUE THREAD

**Issue by LesserBabka** [dmhacker/arch-linux-surface#30]
Have installed this custom kernel on my surface book 2 15" and most of the things are working as expected. However, touchscreen and battery level are not working. Of these, I'm mostly concerned about the touchscreen. Need help to troubleshoot.

$ lsmod
...
intel_ipts             32768  0
...

Should be 1 there, no?

Thank you so much for making this project!

**Comment by dmhacker** [comment]
Actually, intel_ipts should be set to 0 I believe. Can you give me the output of these commands:

`acpi -V`

`dmesg`

`lsmod`

**Comment by phil30000** [comment]
Hi dmhacker

I do believe I have the same issue with the touch screen on the 13" model. I am running manjaro and not base arch so maybe that is the reason, but everything else is running fine. I attached the output of the three commands you asked for:

[acpi.txt](https://github.com/dmhacker/arch-linux-surface/files/3104765/acpi.txt)
[dmesg.txt](https://github.com/dmhacker/arch-linux-surface/files/3104766/dmesg.txt)
[lsmod.txt](https://github.com/dmhacker/arch-linux-surface/files/3104767/lsmod.txt)

Thank you for your great work.

**Comment by adamgajzlerowicz** [comment]
@LesserBabka Is everything else working as expected (keyboard, sound, hibernation/standby)? 

Thanks

**Comment by LesserBabka** [comment]
Thanks for looking into this.

[acpi.txt](https://github.com/dmhacker/arch-linux-surface/files/3114312/acpi.txt)
[dmesg.txt](https://github.com/dmhacker/arch-linux-surface/files/3114313/dmesg.txt)
[lsmod.txt](https://github.com/dmhacker/arch-linux-surface/files/3114314/lsmod.txt)

**Comment by LesserBabka** [comment]
I think most normal things work; keyboard (incl function keys), sound, battery status, track pad (except clicking on the trackpad, maybe thats an option) and except for the touch the monitor works well.

Suspend does not seem to work. Haven't tried hibernation.

**Comment by sebzag** [comment]
dmesg outputs this regarding the touchscreen module:

ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/intel_desc.bin failed with error -2
[    4.514281] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: can't add hid device: -5
[    4.514316] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in handling resp msg

**Comment by sebzag** [comment]
dmesg outputs the following regarding the touchscreen module:

[4.514256] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/intel_desc.bin failed with error -2
[4.514281] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: can't add hid device: -5
[4.514316] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: error in handling resp msg

**Comment by faezs** [comment]
I'm seeing the same dmesg output as @sebzag with 5.0.10-1-surface (sb2 15)

**Comment by v12venator** [comment]
In your mkinitcpio.conf file, you can manually set kernel modules to load in the MODULES=() line, just add "intel-ipts" to that conf file, run mkinitpio on your linux*.img and a reboot should load the ipts module at boot. After adding that module to my .conf file on a Pro 6, I can see the module being loaded and also see it running using the above troubleshooting commands.

**Comment by dmhacker** [comment]
More updates: There are now options in the setup script to populate the MODULES list in the mkinitcpio automatically, which should fix any issues there. The setup script also provides options to install a patched libwacom package as well as install touchscreen, WiFi, and GPU firmware. 

If you run the setup script with these options enabled and then install the latest 5.3.15 kernel and issues still persist, then feel free to reopen this issue or make a new one. Until then, I will leave this closed.
