### ISSUE TITLE
Recompile after each update ?

### ISSUE THREAD

**Issue by NitroBAY** [dmhacker/arch-linux-surface#36]
After every update to the linux kernel on my arch linux I go to  the emergency shell if I use the surface kernel. I found that doing any step like setup.sh/configure.sh or installing binaries  that are not the same version as the regular linux kernel installed doesn't work (emergency shell).
The only thing that works is full recompile from source.
I wonder if I really need to recompile arch-linux-surface kernel after each mainstream kernel update and why ? I thought this kernel would be compiled against its own version of mainstream kernel pulled on the internet not on my computer as if I do uname -r I have 5.0.1-1-surface and not 5.0.14-surface.
So when I compile the result is 5.0.14 or 5.0.1 kernel. If it is the latter why do I need to recompile ?

**Comment by aleksfadini** [comment]
Yes, same for me.

**Comment by dmhacker** [comment]
It's probably because I'm compiling on my own machine, a Surface Book 2. If you're using a Surface Pro *, then it is possible that the pre-compiled kernels won't work; you must compile them. Because I don't have the Surface Pro hardware, I don't really have a viable solution for this. Will keep it open, so I can try and think of something, but for now, you must just compile the kernel yourself.

I'll add a note to the releases section indicating that the kernels are for Surface Books only.

**Comment by aleksfadini** [comment]
Thank you for clarifying this. I'm using your pre-compiled kernel 4.19.27 and it works well for the surface pro 6, it's really helpful to have it there in fact! For some reason the 5.1 freeze intermittently. I am a bit confused on how to patch the kernel on arch and make it look like a package, so this repo is extremely appreciated. Thank you for this.

**Comment by SirSharanChakradhar** [comment]
What do you mean freeze intermittently? Does it freeze for particular apps like opera browser, VSCODE and big apps such? Then, we may have the same issue.

**Comment by aleksfadini** [comment]
The kernel 5 freezes in random moments, when using a terminal or firefox. Not related to big apps. 
I use i3wm so I cannot say if it has to do with the graphics driver or the i7 processor. I have a Surface Pro 6 i5 and that one works fine with any 5 kernel, the freezes happen with the i7 Surface Pro 6 (the high end one). 
However with 4.19 LTS kernel (or any other 4 kernel) everything works well.

**Comment by aleksfadini** [comment]
> It's probably because I'm compiling on my own machine, a Surface Book 2. If you're using a Surface Pro *, then it is possible that the pre-compiled kernels won't work; you must compile them. Because I don't have the Surface Pro hardware, I don't really have a viable solution for this. Will keep it open, so I can try and think of something, but for now, you must just compile the kernel yourself.
> 
> I'll add a note to the releases section indicating that the kernels are for Surface Books only.

Turns out I bought a defective unit! after struggling with kernel freezes and wifi issues I brought it back to the store, exchanged for another SP6 i7 and everything works now. Your pre compiled binares work flawlessly with SP6 i7! Keep them coming!! (You can close this issue for my side of things)

**Comment by dmhacker** [comment]
Wow, that is an interesting resolution to your issue. Guess Microsoft needs to ramp up their QA process. Glad to hear everything works now though!
