### ISSUE TITLE
Got kernel installed, touchscreen doesn't work.

### ISSUE THREAD

**Issue by tylerwolf35** [dmhacker/arch-linux-surface#37]
When I boot into the surface kernel the touchscreen does not work.

I followed the steps and got no errors.

**Comment by WesleyVanNeck** [comment]
Wich device did you run the setup.sh

**Comment by Pommaq** [comment]
What device did you install the kernel on? Was it a surface pro? Surface pro 4? etc.

**Comment by thetylerwolfman** [comment]
> What device did you install the kernel on? Was it a surface pro? Surface pro 4? etc.



> Wich device did you run the setup.sh

Surface Pro 6

**Comment by dmhacker** [comment]
Seems like an upstream issue. It looks like my `setup.sh` follows jakeday's `setup.sh` for installation of IPTS touchscreen drivers for the Surface Pro 6 option.

**Comment by dmhacker** [comment]
Closing issue in 7 days if there are no new developments.

**Comment by dmhacker** [comment]
Try re-running the setup script with mkinitcpio, firmware, and libwacom options selected. Make sure to install the latest kernel version (5.3.15) too.
