### ISSUE TITLE
No directory "hibernate" in linux-surface

### ISSUE THREAD

**Issue by Commander-Firestrike** [dmhacker/arch-linux-surface#4]
In `setup.sh`, "Copy config files from Jakeday's kernel to root?" and answering with "Y" errors with:

```
cp: cannot stat '.cache/linux-surface/root/lib/systemd/system-sleep/hibernate': No such file or directory
Making /lib/systemd/system-sleep/hibernate executable...
chmod: cannot access '/lib/systemd/system-sleep/hibernate': No such file or directory
```

Upon checking the linux-surface repo, there is no sub-directory in `/lib/systemd/system-sleep/`, only a file `linux-surface/root/lib/systemd/system-sleep/sleep`

**Comment by dmhacker** [comment]
Thanks for bringing this to my attention. It looks like jakeday swapped it out for the `sleep` executable. I've updated the setup script to reflect this.
