### ISSUE TITLE
Black screen after hibernation

### ISSUE THREAD

**Issue by azbshiri** [dmhacker/arch-linux-surface#40]
Great job! I installed Manjaro on Microsoft Surface Laptop + your patch, everything works fine except hibernation. Everytime I suspend/hibernate I get black screen or if I leave laptop for a while so I don't how to debug this issue, I mean how to know what should I do to get hibernate working? :D

**Comment by azbshiri** [comment]
resume= was missing on grub config. so I'll close this issue.

**Comment by Augustronic** [comment]
Do you have the dGPU running, too?

**Comment by azbshiri** [comment]
I'm not sure if I have dGPU?
