### ISSUE TITLE
A Failure Occured in prepare()

### ISSUE THREAD

**Issue by SirSharanChakradhar** [dmhacker/arch-linux-surface#41]
```
HEAD is now at d3da1f09fff2 Linux 5.0.10
Applying Arch upstream patches ...
Applying Surface device patches ...
/home/sirsharanchakradhar/arch-linux-surface/build-5.0.10/PKGBUILD: line 53: ../linux-surface/patches/5.0/*.patch: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
┌ 1 ~/arch-linux-surface/build-5.0.10 (master=) 
└> $ 
```

Any idea what to do?

**Comment by ShapeShifter499** [comment]
I got a similar error but it mentions

```
line53: ../linux-surface/patches/5.0/*,patch: No such file or directory"

**Comment by SirSharanChakradhar** [comment]
You can install 4.xx kernel. It will work. Now I’m getting /boot space issue. Any idea? Also I don’t think the script will change or replace the config to new kernel. 

I felt this when there was no space, so I deleted the vmlinux kernal. Later the setup finished, I rebooted the system and it was asking for vmlinux kernal.

Anyways I’m a newbie in terms of Linux core. I’m not pretty much sure of what I did.

**Comment by ShapeShifter499** [comment]
@dmhacker Your stuff is out of date, that's why I'm hitting an error.  Jakeday has already pushed 5.1.7.  Can you please update this?

**Comment by ShapeShifter499** [comment]
@SirSharanChakradhar Sounds like the partition that /boot is stored on has literally run out of space. Meaning when the system tries to install the compiled kernel there isn't enough space on /boot to put the files into.

**Comment by SirSharanChakradhar** [comment]
Ok
