### ISSUE TITLE
Nothing working after new kernel installation

### ISSUE THREAD

**Issue by SirSharanChakradhar** [dmhacker/arch-linux-surface#43]
I have compiled the kernel and installed it and rebooted. It didn't take any drivers. Only touchpad and wifi were working before and after reboot also same. 

What should I do?

**Comment by 33Fraise33** [comment]
I had the same issue, a new release has been pushed which is working, I haven't been able to build myself successfully

**Comment by SirSharanChakradhar** [comment]
I was just thinking it to redo it tonight. Thanks for the info though.

**Comment by SirSharanChakradhar** [comment]
I tried the pre-built kernel and nothing worked. I'm gonna compile the whole kernel and check once again now. 

I tried first step and last step with new precompiled kernel. 
I will try 2nd and 3rd step now.

**Comment by 33Fraise33** [comment]
Be sure to run the setup.sh in this repo. Installing the compiled kernel has always worked for me: 

'yay -U linux-surface-headers-5.1.7-1-x86_64.pkg.tar.xz linux-surface-docs-5.1.7-1-x86_64.pkg.tar.xz linux-surface-5.1.7-1-x86_64.pkg.tar.xz
'

**Comment by SirSharanChakradhar** [comment]
@33Fraise33 , Thanks for the info. The script didn't set default kernel in the grub. So, when it is booted it was taking the generic kernel which comes from distro. I used Grub Customizer to change the settings & bam, it worked like never before. I hope this will help others who had the problem.
