### ISSUE TITLE
200 % Display Scaling not working on IBM SPSS 26 and Spotify

### ISSUE THREAD

**Issue by lx07** [dmhacker/arch-linux-surface#48]
200 % Display Scaling not working on IBM SPSS 26 and Spotify.
Both apps upscale to 2736x1824.

Is there a fix?
Thx

**Comment by dmhacker** [comment]
This probably isn't related to a kernel or installation issue, so I am going to close it. But to answer your problem, maybe try fiddling around with xrandr settings (increase DPI, etc.). Also, take a look at https://wiki.archlinux.org/index.php/HiDPI. Seems like they have a section for Spotify; not sure about IBM SPSS 26.
