### ISSUE TITLE
[Surface 3] Touchscreen not working after kernel install

### ISSUE THREAD

**Issue by albttx** [dmhacker/arch-linux-surface#49]
Hello,

Before installing the custom kernel, touchscreen seems to work, but after install the custom kernel, it's not woking anymore

Under `What Surface model is your device?`

I selected `Surface Pro 3`, i also tested with `Surface Book`.

Which one should i select ? Or can i remove it ?

Thanks

**Comment by albttx** [comment]
Surface model is: https://www.backmarket.fr/microsoft-surface-3-10-atom-x7-z8700-16-ghz-ssd-64-go-ram-4-go-qwerty-pas-cher

**Comment by SirSharanChakradhar** [comment]
@albttx , Did you choose the custom kernal during the booting  in grub? If not you can use grub customizer to set the Linux Surface kernel as default.

**Comment by albttx** [comment]
Yes, `uname -a` return me the good kernel.

But while doing a `sudo pacman -Syu` everthing got broken and the ssd isn't discover (i usb boot, and i don't see it with `fdisk -l`

byebye surface 👋

**Comment by motorto** [comment]
Touchscreen and pen input still doesn't work after enabling the kernel running archlabs if it matters on a surface pro 2017

**Comment by dmhacker** [comment]
Please see issue #79 and try re-running the setup script to update mkinitcpio, install the latest firmware, and build the libwacom patched package. We are no longer using model-specific firmware options.
