### ISSUE TITLE
4.18

### ISSUE THREAD

**Issue by lewisfff** [dmhacker/arch-linux-surface#5]
This works really well for me, I would like to try 4.18 as I believe it might fix the touchpad jumping issue, but the setup is a bit beyond me.

Would be awesome if this package could be updated to reflect https://github.com/jakeday/linux-surface/releases/tag/4.18.7-2

**Comment by dmhacker** [comment]
Done! You can also find the prebuilt binary in the [releases section](https://github.com/dmhacker/arch-linux-surface/releases).
