### ISSUE TITLE
[Surface pro 2017] Touchscreen and pen input dont work

### ISSUE THREAD

**Issue by motorto** [dmhacker/arch-linux-surface#53]
Hey guys tried with manjaro and arch build from scratch and the kernel simply didnt make the touchscreen or the pen input work. Just letting you guys know

**Comment by TechDroid2002** [comment]
run setup.sh

**Comment by motorto** [comment]
No I fixed it , probably at the end of the guide should have the comand to update grub

**Comment by dmhacker** [comment]
I'll see about adding something about grub. Have been trying to keep the guide as bootloader-agnostic as possible however.
