### ISSUE TITLE
[Surface Pro 2017] Touchscreen not working - kernel 5.1.15-1

### ISSUE THREAD

**Issue by mlazzarotto** [dmhacker/arch-linux-surface#54]
Hello, I've just installed Manjaro **18.0.4** on my Microsoft **Surface Pro 2017** version and downloaded every update possible.
I installed the prebuilt **5.1.15-1** kernel packages and I'm sure I'm booting with that kernel.
However the touchscreen is not working.

Am I missing some step? Should I run anyway the setup.sh?

Thank you

**Comment by dmhacker** [comment]
Try running this setup script, selecting yes to options 2 and 4 (rebuild kernel with mkinitcpio modules, install firmware). You can also try installing the patched libwacom package from [here](https://github.com/qzed/libwacom-surface).

Since this thread is somewhat old, going to close it.
