### ISSUE TITLE
Eraser not working 

### ISSUE THREAD

**Issue by motorto** [dmhacker/arch-linux-surface#58]
The eraser on the pen works as another pen , this issue doesnt happen on jakedays kernel installed on debian based systems , only on archb

**Comment by mfauvain** [comment]
Had same issue after upgrading libinput. See here : https://github.com/jakeday/linux-surface/issues/557

**Comment by dmhacker** [comment]
Closing this issue because this is likely something that I cannot fix via this repository. Refer to StollD's daemon service if you want a workaround (or try to downgrade libinput).
