### ISSUE TITLE
Support for qzed's fork of linux-surface

### ISSUE THREAD

**Issue by dmhacker** [dmhacker/arch-linux-surface#61]
@qzed

Seeing as jakeday has been rather inactive for linux-surface and qzed's fork seems to be an actively-maintained replacement, I am going to create a separate branch for tracking and applying those patches. Will post updates here and close the issue once it's live.

**Comment by qzed** [comment]
First off, thank you for your work!

As I'm an Arch user myself, I'll be uploading pre-built Arch kernel packages alongside the Debian packages (configs can be found [here](https://github.com/qzed/linux-surface-kernel-configs)), and thanks to @StollD we have also set up a custom [Arch repository](https://github.com/qzed/linux-surface/wiki/Package-Repositories#arch-linux-repository) for them (which will hopefully be updated shortly, as soon as I get around to packaging a new set of kernels). For the Surface Book 2, the utility packages (`surface-control` and `surface-dtx-daemon`) as well as a patched libwacom fork (`libwacom-surface`) are on AUR.

That, however, concludes my immediate plans for Arch Linux support. While I have a PKGBUILD for the kernel, this is very customized and tailored to my needs, focusing more on development. It would be great to have one around for people wanting to build the kernel themselves. Also, as my fork will still be mainly Debian focused, so a setup script adapted to Arch will keep its usefulness.

Also feel free to forward any non-Arch-specific issues to jakeday/linux-surface, we will still try to fix them.

**Comment by dmhacker** [comment]
Oh ok, great! I'll definitely make a note of your build system in the new README. I think I'll keep maintaining this to ease any dependent users on to your version, as well as keep the setup script active like you mentioned. Will keep you posted for sure both about this and any non-Arch-related issues.

**Comment by qzed** [comment]
Thanks, sounds great!

**Comment by Augustronic** [comment]
> While I have a PKGBUILD for the kernel, this is very customized and tailored to my needs, focusing more on development.

Is this the reason my SB2 doesn't show a Nvidia card with your kernel?

**Comment by qzed** [comment]
That's because I decided to power it off by default, due to needless power-consumption in most cases (via the surfacebook2_dgpu_hps module). Also it tends to get warm if it is powered on, even if you don't use it at all. If you want to use it for certain applications only, have a look at https://github.com/jonnyr2008/linux-surfacebook2-mshw0153#setting-up-the-dgpu-for-use-with-bumblebee-and-the-official-nvidia-driver-on-arch-linux. You can also enable it permanently by setting module parameters as described in the same readme.

**Comment by aleksfadini** [comment]
This is wonderful.
Is there a way to add a patch for the Surface Pro 7, that would otherwise work well with the latest release of linux-surface from your repo?

Reference here:
https://github.com/jakeday/linux-surface/issues/592

**Comment by dmhacker** [comment]
`master` branch has been updated to now track qzed's repository. The `jakeday` branch will continue to track jakeday's repository.

Notes about qzed's Arch repository and the new changes have been added to the README.
