### ISSUE TITLE
Patch for 5.3

### ISSUE THREAD

**Issue by tworzenieweb** [dmhacker/arch-linux-surface#66]
Hi,

do you think missing patch files can be added to the repository?

Plus I think it makes sense to replace the source to

https://github.com/qzed/linux-surface/commits/master

since the original one is not maintained for a long time.

Best Regards and thank you for hard work!

**Comment by dmhacker** [comment]
Addressed. Default `master` branch has been updated to track qzed's fork. `jakeday` branch will continue to track the original repository.
