### ISSUE TITLE
SB2 Volume buttons not working

### ISSUE THREAD

**Issue by vonAlenberg** [dmhacker/arch-linux-surface#7]
Running `` 4.18.8-1-surface`` and have no volume buttons working. They did work when I was using jakedays kernel on Ubuntu 18.04 (4.17.3 I think).
If you need further logs just tell me.

**Comment by dmhacker** [comment]
Like your other issue, I think this is an issue with the newer versions of jakeday's kernel, not necessarily something that's wrong with my patching utility itself. I'll mark this as a potential bug for now, but I won't promise any immediate fixes.

**Comment by qzed** [comment]
Can be closed, fixed as of https://github.com/jakeday/linux-surface/pull/252.
