### ISSUE TITLE
error when run command: MAKEFLAGS="-j[NPROC]" makepkg -sc

### ISSUE THREAD

**Issue by ricardo17coelho** [dmhacker/arch-linux-surface#72]
![20191116_105146](https://user-images.githubusercontent.com/37732431/68991434-2ee69480-085f-11ea-9ad3-6c665e0377c5.jpg)
see errors in the attached image.

**Comment by theailer** [comment]
Hi,
You are missing a command called patch. But you are probably missing most of the commands required to build the kernel. Try to do a
pacman -S patch bison flex make gcc

**Comment by ricardo17coelho** [comment]
it works. thx
