### ISSUE TITLE
can't mount drive after reboot

### ISSUE THREAD

**Issue by ricardo17coelho** [dmhacker/arch-linux-surface#74]
![20191117_124431](https://user-images.githubusercontent.com/37732431/69050517-82ddae80-0a02-11ea-9aa4-4cfaac31f15d.jpg)
after successfully install the compiled files and reboot the system can't go into the arch-os

(see attached image)

i'm using  rEFInd as boot manager
can someone help me ? thx!

**Comment by ricardo17coelho** [comment]
?

**Comment by dmhacker** [comment]
I think this is more of an issue with your rEFInd setup than with this repository. See here:
https://bbs.archlinux.org/viewtopic.php?id=212129

You be might be trying to boot from an out-of-date stub, which is causing rEFInd to drop you into an emergency shell. Use the fix that they suggested or boot directly from grub.
