### ISSUE TITLE
optimus-switch-gdm

### ISSUE THREAD

**Issue by Augustronic** [dmhacker/arch-linux-surface#75]
Will [dglt1/optimus-switch-gdm](https://github.com/dglt1/optimus-switch-gdm) work with [qzed/linux-surface pre-build kernel](https://github.com/qzed/linux-surface/releases) or will I have to compile an own?

**Comment by dmhacker** [comment]
Theoretically, I think it should if you're running Manjaro. Haven't tested it however.

I'm going to close this question for now unless you encounter any bugs specific to the Surface kernel.
