### ISSUE TITLE
Kernel 5.3 has problems being compiled with DistCC

### ISSUE THREAD

**Issue by skogsmaskin** [dmhacker/arch-linux-surface#76]
Hi! First, thanks for providing this great Arch Linux package for the Surface kernel.

This is not really an issue with the PKGBUILD, but rather an issue with distcc (or the kernel source), but I thought I'd report it as I just wasted a couple of hours trying to debug it, and it might help others running into this problem.

I compile my kernel with distcc and this worked fine with Kernel 5.1. However trying to compile 5.3 I ran into some strange issues where it got an invalid response from the distcc server, and it would just end up compiling locally instead, without any usable debug info.

After some heavy googling, I found others who have run into the same problems for distcc compiling kernel version `>=5.2.0`. The solution (for now) seems to be to edit the  PKGBUILD to make the build step with:

`make bzImage modules CC=distcc CXX=distcc`
instead of just
`make bzImage modules`

Feel free to close this, as it's really not an issue with `arch-linux-surface`, but I think it would be great to have it noted somehwere (like here) because I'm probably not the only one doing the compilation with distcc. 

The bug:
https://bugs.archlinux.org/task/64275
https://github.com/distcc/distcc/issues/358

Thanks!

**Comment by dmhacker** [comment]
Thanks for the information! Closing the issue as noted.

Feel free to comment on and reopen this anytime if something changes.
