### ISSUE TITLE
Update the PKGBUILD

### ISSUE THREAD

**Issue by archseer** [dmhacker/arch-linux-surface#78]
The upstream PKGBUILD was simplified a lot since this repo last pulled it in:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/linux

It will automatically apply any `.patch` files so all you have to do is list them under sources.

**Comment by archseer** [comment]
Also the mkinitcpio hooks are now built into pacman: https://www.archlinux.org/news/new-kernel-packages-and-mkinitcpio-hooks/

**Comment by dmhacker** [comment]
I'll work on this next.

**Comment by archseer** [comment]
For newer generations I'm maintaining PKGBUILDs with minimal changes from upstream, might be of help https://github.com/archseer/arch-linux-surface

**Comment by Imp-Byte** [comment]
An Issue has been created when doing setup.sh.
Heres the output...


5. Install device-specific firmware (touchscreen, wireless, GPU)? [y/N] y
What Surface model is your device? Enter the number corresponding to your selection.
1) Surface Pro 3         3) Surface Pro 4        5) Surface Pro 6        7) Surface Laptop       9) Surface Book        11) Surface Book 2 15"
2) Surface Pro           4) Surface Pro 2017     6) Surface Studio       8) Surface Laptop 2    10) Surface Book 2 13"  12) Surface Go
#? 11
Surface Book 2 15" selected. Installing firmware ...
Unpacking files to /lib/firmware/intel/ipts/ ...
unzip:  cannot find or open .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip, .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip.zip or .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip.ZIP.
Unpacking files to /lib/firmware/i915/ ...
unzip:  cannot find or open .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip, .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip.zip or .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip.ZIP.
Unpacking files to /lib/firmware/nvidia/gp108/ ...
unzip:  cannot find or open .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip, .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip.zip or .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip.ZIP.

Removing temporary cache ...

Setup process finished!
Install your patched kernel and then reboot.
[imp@kleinbyte arch-linux-surface]$

**Comment by limeless** [comment]
> An Issue has been created when doing setup.sh.
> Heres the output...
> 
> 1. Install device-specific firmware (touchscreen, wireless, GPU)? [y/N] y
>    What Surface model is your device? Enter the number corresponding to your selection.
> 
> 1. Surface Pro 3         3) Surface Pro 4        5) Surface Pro 6        7) Surface Laptop       9) Surface Book        11) Surface Book 2 15"
> 2. Surface Pro           4) Surface Pro 2017     6) Surface Studio       8) Surface Laptop 2    10) Surface Book 2 13"  12) Surface Go
>    #? 11
>    Surface Book 2 15" selected. Installing firmware ...
>    Unpacking files to /lib/firmware/intel/ipts/ ...
>    unzip:  cannot find or open .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip, .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip.zip or .cache_setup/linux-surface/firmware/ipts_firmware_v101.zip.ZIP.
>    Unpacking files to /lib/firmware/i915/ ...
>    unzip:  cannot find or open .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip, .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip.zip or .cache_setup/linux-surface/firmware/i915_firmware_kbl.zip.ZIP.
>    Unpacking files to /lib/firmware/nvidia/gp108/ ...
>    unzip:  cannot find or open .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip, .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip.zip or .cache_setup/linux-surface/firmware/nvidia_firmware_gp108.zip.ZIP.
> 
> Removing temporary cache ...
> 
> Setup process finished!
> Install your patched kernel and then reboot.
> [imp@kleinbyte arch-linux-surface]$
> 
> Note: I do have zip unzip installed

I have the same problem but it seems like the script clone the qzed's repo which doesn't contain those zip files, try change the repo to jakeday's and try again.

**Comment by dmhacker** [comment]
@Imp-Byte @limeless Try running the latest setup script. qzed made some changes to the structure of the firmware directories, no model-specific options are required anymore.

**Comment by limeless** [comment]
> @Imp-Byte @limeless Try running the latest setup script. qzed made some changes to the structure of the firmware directories, no model-specific options are required anymore.

thank you for the fast reply, I can confirm the latest script will complete without problems.
but where should I find patched kernel to install as last message said :
> "Setup process finished. Install your patched kernel and then reboot."

**Comment by dmhacker** [comment]
As commit 9414968, the latest PKGBUILD has been integrated into this repository. I've change how the compilation setup script works, such that the appropriate patches are soft linked directly to the build directory and are referenced in the PKGBUILD (rather than the PKGBUILD looping through external directories). This means that future PKGBUILDs are edited pretty minimally. 

Closing this now. Issues about the touchscreen and whatnot should be addressed separately.
