### ISSUE TITLE
[Question] Pre-compiled binaries and setup.sh

### ISSUE THREAD

**Issue by KuriosCurious** [dmhacker/arch-linux-surface#80]
This is just a curiosity question as documentation everywhere is unclear to me.
Is there a point in running setup.sh if you're just installing the pre-compiled kernels? I'm curious if any of the questions even matter at that point.

Thanks

**Comment by v12venator** [comment]
No, if you are using the pre-compiled binaries, you do not need to run setup.sh. That is only if you are wanting to change suspend to hibernate or make sure your device's firmware and drivers are installed.

**Comment by dmhacker** [comment]
Like @v12venator said, setup.sh is useful if you want to make sure firmware/drivers are installed or if you want to change suspend to hibernate (among some other options). It's designed so that it will prompt for each action, so you can selectively install drivers, etc.
