### ISSUE TITLE
[Surface Book 2] Touchscreen not working

### ISSUE THREAD

**Issue by KuriosCurious** [dmhacker/arch-linux-surface#81]
As title says, touchscreen doesn't work. This is a fresh install of Manjaro on this Surface Book 2.
I followed this [Fix] here https://github.com/dmhacker/arch-linux-surface/issues/56
Also tried installing pre-compiled binary.

**Comment by dmhacker** [comment]
Can you try running the setup script again in conjunction with the 5.13.15 kernel? I've updated the firmware, libwacom, and mkinitcpio options.

**Comment by dmhacker** [comment]
Closing this unless there are further updates.
