### ISSUE TITLE
Error: module surface_acpi not found

### ISSUE THREAD

**Issue by v12venator** [dmhacker/arch-linux-surface#82]
When trying to upgrade kernel from 5.1.15-1 to 5.3.10-1 I noticed that this error popped up during Pacman install of the kernel tar.xz 

This happened with both compiling the kernel and your pre-compiled binaries on a surface pro 6.

I downgraded back to 5.1.15-1 to make sure I was still stable and had backups of that kernel's binaries in the event of the 5.3.10 kernel being unable to boot.

I have not yet tried booting into this kernel with the error to see what will happen, but I will do this later this evening and report back what happens.  

Edit: For reference, self compiling and pre-compiled kernels of this version worked flawlessly on a fresh install on a surface go.

**Comment by PandorasFox** [comment]
the surface_acpi module was renamed to surface_sam; you'll need to update the mkinitcpio to include the correct modules now (see https://github.com/qzed/linux-surface/commit/d065c13cca40150db4bc8e1592edf28faec0c173)

**Comment by v12venator** [comment]
@PandorasFox thank you, I'll take a look at that repo this evening when I get home and report back on how it goes.

**Comment by dmhacker** [comment]
Merging all issues related to the surface_acpi/surface_sam split to issue #73. Will fix after my finals (ETA one week).
