### ISSUE TITLE
[Surface Laptop 3] Keyboard and touchpad don't seem to work

### ISSUE THREAD

**Issue by klemag** [dmhacker/arch-linux-surface#84]
I've run the latest version (d3318d2c) of the setup.sh and compile_setup.sh with kernel 5.3, installed it -- the scripts worked fine** and I was able to boot on it but unfortunately touchpad and keyboard still don't seem to work. Have I missed anything? Is SL3 supposed to be supported already?

** I just had errors in the setup.sh with the following modules not found, but the module for keyboard seem to be found fine

```
==> ERROR: module not found: `intel_ipts'
==> ERROR: module not found: `surface_sam_ssh'
==> ERROR: module not found: `surface_sam_san'
==> ERROR: module not found: `surface_sam_vhf'
```

**Comment by dmhacker** [comment]
What's the output of `uname -v`?

**Comment by klemag** [comment]
@dmhacker it says `5.3.15-1`; not sure why there is no `surface` as I booted on the `linux linux-surface` kernel from grub. I genereted the grub config `grub-mkconfig -o /boot/grub/grub.cfg` and the entry `Arch Linux, with Linux linux-surface` points to `/boot/vmlinux-linux-surface` which seems correct (?)

I've noticed you made new updates so I tried to re-compile and install, now `uname -r`  shows `5.18.10-1-surface` but the keyboard still doesnt work.

**Comment by dmhacker** [comment]
Can you try updating to the 5.3.18 kernel? Have you installed all firmware and the libwacom-surface package?

**Comment by klemag** [comment]
My bad, I made a typo above, i meant to say I've installed and tried kernel `5.3.18-1-surface`  (and checked with `uname -r` that it's running the right kernel). I've installed all firmware through the `setup.sh` script -- answered `y` to all and installed libwacom-surface from https://aur.archlinux.org/libwacom-surface.git , unfortunately that did not solve the keyboard issue.

**Comment by dmhacker** [comment]
I'm not sure why the keyboard isn't working then. It could be that the kernel doesn't support the SL3 yet. Maybe @qzed can help.

**Comment by archseer** [comment]
The kernel should support the SL3 keyboard, I wrote the patch for it. Make sure to run the 5.4 version of the kernel though:

- 5.3 contains a reverted i915 driver which can cause issues on the newer devices (https://github.com/linux-surface/linux-surface/issues/23)
- 5.4 contains a handful of Ice Lake specific stuff that makes things like the power button work
- 5.4 lacks the ipts driver which breaks touchscreen, but the newer devices use a different protocol so it won't work with the 5.3 driver anyway

**Comment by klemag** [comment]
Thanks both! I had a look at the `compile_setup.sh` script, looks like I'm only missing the file `base/configs/config5.4` to install the kernel using @dmhacker 's script, any idea how I can generate this config?

**Comment by dmhacker** [comment]
You can find that file [here](https://github.com/archseer/arch-linux-surface/blob/master/kernel/config), just `wget` the raw version as the`base/config/config.5.4` file you mentioned earlier. I'll add this to the repository later tonight.

**Comment by klemag** [comment]
Thanks -- for some reason when re-building it and installing, keyboard still didn't work, but after installing  v5.4.6-1 directly from https://github.com/linux-surface/linux-surface/releases it worked fine. So I was probably doing something wrong :/ 

Btw, @dmhacker in order to add 5.4 to the compile_setup.sh, it looks like you're missing it in the options line 8

Closing the issue :)

**Comment by dmhacker** [comment]
It could be that I gave you the wrong config actually, since that's the base config for the unpatched 5.4.1 kernel. Using [this one](https://github.com/linux-surface/kernel-configs/blob/master/5.4/generated/arch-surface-5.4-x86_64.config) might give you better results. I've updated the repository with it.

Regardless, glad you got it working!
