### ISSUE TITLE
setup.sh script libwacom PKGBUILD error

### ISSUE THREAD

**Issue by BeatScherrer** [dmhacker/arch-linux-surface#86]
commit 94149680bb6577d0056c51daea245d1024d89423

the `setup.sh` script tries to run `makepkg` and apparently does not find a PKGBUILD file:
```
5. Would you like to replace libwacom with its patched version? [y/N] y
Building and installing the patched version of libwacom ...
==> ERROR: PKGBUILD does not exist.
Done installing patched libwacom.
```

**Comment by qzed** [comment]
That's kind of my fault: I've removed the PKGBUILD from https://github.com/linux-surface/libwacom-surface-patches due to some changes in the repo organization. The libwacom-surface package can now be found on AUR: https://aur.archlinux.org/packages/libwacom-surface/.

**Comment by dmhacker** [comment]
Updated the option to print out a link to the package on the AUR rather than actually install stuff. That way, people can use their own AUR helper to install it.
