### ISSUE TITLE
Fix for non-working eraser!!! (tested on SP6)

### ISSUE THREAD

**Issue by xypwn** [dmhacker/arch-linux-surface#88]
As already mentioned by a previous issue, the eraser on the Surface Pen is not recognized as such but rather as a normal pen. After doing a bit of research around libinput and the different versions, I found out that **the pen works perfectly fine when using the current git libinput version (1.15.0)**.
Thankfully, someone made an AUR package so here is how to install it:

1. Forcefully remove the current version (WARNING: make sure that the system stays on while no libinput version is installed): `sudo pacman -Rdd libinput`
2. Install libinput-git from aur
    - **If it asks you to import keys,** _type n for no_
    - Using yay: `yay -S libinput-git`
    - Manually: `git clone https://aur.archlinux.org/libinput-git.git && cd libinput-git && makepkg -i`
3. **IMPORTANT:** The git version is very unstable so if it stops working or if the official repos update to version 1.15.0, reinstall the normal version with: `sudo pacman -S libinput`

**Comment by archseer** [comment]
Yeah it was recently fixed: https://gitlab.freedesktop.org/libinput/libinput/issues/259

**Comment by dmhacker** [comment]
Closing this since it looks to be resolved externally!
