### ISSUE TITLE
error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by Putaro2** [dmhacker/arch-linux-surface#9]
This happend on both versions (4.14 and 4.18) when I am compiling the kernel.

 -> Updating linux-stable git repo...
error: cannot open .git/FETCH_HEAD: Permission denied
==> WARNING: Failure while updating linux-stable git repo
  -> Updating linux-surface git repo...
error: cannot open .git/FETCH_HEAD: Permission denied
==> WARNING: Failure while updating linux-surface git repo
  -> Updating linux-surfacegen5-acpi-notify git repo...
error: cannot open .git/FETCH_HEAD: Permission denied
==> WARNING: Failure while updating linux-surfacegen5-acpi-notify git repo

Is it irrelevant or am i doing something wrong here? I already used chown and chmod but no changes.

It's running through completly, but in the end my surface books touchscreen (yet it did on v4.18.8) won't work...

**Comment by dmhacker** [comment]
This is confusing. Since it's giving permission denied errors specifically with respect to the FETCH_HEAD, this leads me to believe that it is an issue with the permissions of the **.git** directory for each of the cached repositories. Try `chown -R [username] .cache/[repository]/.git` for each of the three repositories it checks out. If that fails, try deleting the **.cache** folder in the root repository directory and rerun the setup script.

**Comment by Putaro2** [comment]
ok, that worked, but still no touchscreen

i tried it running gnom on xorg and on wayland. on xorg it's not recognised as an touch input, on wayland it is recognised but still no touch on both.
Then i reinstalled arch on my surface book, ran the kernel update again and still the same problem....

**Comment by dmhacker** [comment]
Did you try running the **setup.sh** script in the main directory to install the IPTS firmware?

**Comment by Putaro2** [comment]
yes, i did run it and chose 'y' (also ran it again when i realised it still does not work) and then 5) Surface Book.

**Comment by dmhacker** [comment]
Interesting. What Surface model are you using? I'm using the Surface Book 2 15' and it seems to be working fine for me.

**Comment by Putaro2** [comment]
my grub.cfg looks wrong here: 

 ```
### BEGIN /etc/grub.d/10_linux ###
menuentry 'Arch Linux' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-b2468715-eade-4354-ab2c-862655d668dd' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root  b2468715-eade-4354-ab2c-862655d668dd
	else
	  search --no-floppy --fs-uuid --set=root b2468715-eade-4354-ab2c-862655d668dd
	fi
	echo	'Loading Linux linux ...'
	linux	/boot/vmlinuz-linux root=UUID=b2468715-eade-4354-ab2c-862655d668dd rw  quiet
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initramfs-linux.img
}
```

but not sure if that's the issue since i really don't know anything about kernels
