### ISSUE TITLE
[Surface 2017 Manjaro] Touchscreen not working and build errors

### ISSUE THREAD

**Issue by Dranion** [dmhacker/arch-linux-surface#93]
Trying to installl linux-surface-5.4.6.-1-x86_64.pkg.tar.xz. 
I ran shsetup to no errors that I can see: [shsetup.txt](https://github.com/dmhacker/arch-linux-surface/files/4087736/shsetup.txt)

Then installed linux-surface-headers-5.4.6-1-x86_64.pkg.tar.xz and linux-surface-5.4.6-1-x86_64.pkg.tar.xz. On attempting to build 5.4.6.-1-surface it threw an error:
`==> ERROR: module not found: 'intel_ipts'`
`==> Generating module dependencies`
`==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface-fallback.img`
`==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly`

and also failed to find nvme0n1, which is my hard disk I believe? 
`/usr/bin/grub-probe: warning: unknown device type nvme0n1.`

[Full file of running pacman -U on those](https://github.com/dmhacker/arch-linux-surface/files/4087742/pacmanu.txt)

For reference I'm currently running Manjaro Linux 18.1.5 Juhraya with the 5.3.18-1-surface kernel. Fairly new to arch so not sure if this is even an important error or not. It did finish building the kernel in the end (`done`). 

Edit: Once I rebooted and was indeed running 5.4.6-1-surface, the touchscreen no longer works, which makes sense considering what intel_ipts is for. Following [issue#56](https://github.com/dmhacker/arch-linux-surface/issues/56) I attempted to re-run setup.sh, which ran identically except for throwing an error: `==> ERROR: module not found: 'intel_ipts' `.

**Comment by Sebboo** [comment]
Same issue kept showing up for me after updating to the latest version. Touchscreen and pen were working fine on the previous version without any errors.

**Comment by dmhacker** [comment]
Unfortunately, touchscreen is broken for 5.4.6 kernels. You would have to downgrade to 5.3.18 in order to be able to use it.

**Comment by bDarbonne** [comment]
I'm having the same issue. My kernel is: 5.5.7-arch1-1. I'm ok with doing without, and would like to know if there is a way to just remove this from the latest "linux-surface-5.5.7-1-x86_64.pkg.tar.xz". I am very much a noob at handling linux drivers and the kernel, but willing to learn.

**Comment by acschill** [comment]
I'm on linux-surface-5.5.13 with touchscreen working - try updating?

**Comment by lordmoonvalks** [comment]
@acschill how did u get touchescreen to work ? Im on surface laptop 2 managed to fix keyboard and to get it work on encryption login screen but intel_ipts module is not found so i cannot initialize the latest kernel, the older kernels work but the multi touch doesnt work still

**Comment by Dranion** [comment]
@lordmoonvalks (since aschill hasn't responsed) as of now, 5.5.x continues to not support multi-touch. My original issue was that no touchscreen function (neither pen nor single-touch) was working, which has since been resolved in future updates. I assume this is similarly the case with acschill. If you need multitouch, consider downgrading to 5.3.18 or the LTS release (4.19). 

I'm gonna close this issue since the original issue is no longer really a problem.
