### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by Adwerk** [dmhacker/arch-linux-surface#94]
During Pre-installation the guide states ..

> Before you begin compiling & installing the patched kernel, it's recommended that you install all necessary firmware that your Surface device needs and replace suspend with hibernate. You can do this by running the setup.sh script WITHOUT superuser permissions.

Are we talking about actually patching the surface firmware? Or is this a simple matter of drivers and the like?

I know the questions a bit dumb, but I just wanna be absolutly certain I don't screw up the firmware on my unit.

**Comment by Adwerk** [comment]
Nvm, installed it :)
Touch and pen doesnt seem to work (tried rerunning the setup without luck), but I guess thats work in progress for my part. Thanks for the work you put into this.

**Comment by dmhacker** [comment]
Glad to hear you got it working. If you installed the 5.4.6 build, touchscreen will not work because IPTS support is broken. You would have to downgrade to 5.3.18.

**Comment by Adwerk** [comment]
It was the newest build, the downgraded works fine. Once again, thanks :)
